export const tagTypes: string[] = [
    "phones", 
    "phone",
    "tablets",
    "tablet",
    "laptops",
    "laptop",
    "televisions",
    "television",
    "reviews",
    "review",
    "support",
    "support-messages",
    "support-single-message",
    "wishlist",
    "single-wishlist",
    "cart",
    "cart-articles"
];